# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: touch .env
    - run: echo NEXT_PUBLIC_SANITY_DATASET=production >> .env
    - run: echo NEXT_PUBLIC_SANITY_PROJECT_ID=${{secrets.SANITY_KEY}} >> .env
    - run: echo NEXT_PUBLIC_BASE_URL=http://localhost:3000 >> .env
    - run: npm install
    - run: cd sanity  
    - run: npm install
    - run: npm run start
    - run: cd ..
    - run: npm run start
